services:
  task-admin-backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: task-admin-dev-backend:latest
    container_name: task-admin-backend-dev
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/usr/src/app
      # not overriding node_modules to avoid conflicts
      - /usr/src/app/node_modules
    environment:
      - .env.dev
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: task-admin-mongo-dev
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo-data-dev:/data/db

volumes:
  mongo-data-dev:
    driver: local
